config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "/home", to: "pages#home"
  get "/projects", to: "pages#projects"
  get "/contact", to: "pages#contact"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def projects
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TuApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <%= link_to 'Mi Portafolio', root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to 'Home', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Projects', projects_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Contact', contact_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>



  
  <div class="container">
    <%= yield %>
  </div>

  <%= javascript_include_tag "application" %>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>
<h2>Contacto</h2>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<h2>Home</h2>

app/views/pages/projects.html.erb
<div class="container">
  <h1>My Projects</h1>
  <div class="row">
    <div class="col-md-4">
      <div class="card">
        <%= image_tag "imagen1.jpeg", class: "card-img-top", alt: "Project 1" %>
        <div class="card-body">
          <h5 class="card-title">Project 1</h5>
          <p class="card-text">Project 1 description</p>
          <a href="#" class="btn btn-primary custom-btn">Ver más</a>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card">
        <%= image_tag "imagen2.jpeg", class: "card-img-top", alt: "Project 2" %>
        <div class="card-body">
          <h5 class="card-title">Project 2</h5>
          <p class="card-text">Project 2 description</p>
          <a href="#" class="btn btn-primary custom-btn">Ver más</a>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card">
        <%= image_tag "imagen3.jpeg", class: "card-img-top", alt: "Project 3" %>
        <div class="card-body">
          <h5 class="card-title">Project 3</h5>
          <p class="card-text">Project 3 description</p>
          <a href="#" class="btn btn-primary custom-btn">Ver más</a>
        </div>
      </div>
    </div>
  </div>
</div>